import nextVitals from "eslint-config-next/core-web-vitals";
import nextTypescript from "eslint-config-next/typescript";

const config = [
  ...nextVitals,
  ...nextTypescript,
  {
    // The copy-in assistant-ui components are generated by `npx assistant-ui add`;
    // keep them byte-identical to upstream rather than re-linting them here.
    ignores: [".next/**", "components/assistant-ui/**", "components/ui/**", "hooks/**"],
  },
];

export default config;
